import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom'
import { Welcome } from '../pages/Welcome'
import { MainLayout } from '../components/layouts'
import { DepartmentPage, DistrictPage, PaymentPage, ProvincePage, UsersTable, ModulesPage, ChannelsPage, ManagementsPage, LoginPage } from '../pages'

export const Routers = () => {
  return (
        <BrowserRouter>
            <Routes>
            <Route
          path="/"
          element={<Navigate to="/start" />}
        />
          <Route
            path='/users'
            element={
            <MainLayout>
              <UsersTable
              />
            </MainLayout>
        }
          />
          <Route
            path='/department'
            element={
            <MainLayout>
              <DepartmentPage
              />
            </MainLayout>
        }
          />
          <Route
            path='/province'
            element={
            <MainLayout>
              <ProvincePage
              />
            </MainLayout>
        }
          />
          <Route
            path='/district'
            element={
            <MainLayout>
              <DistrictPage
              />
            </MainLayout>
        }
          />
          <Route
            path='/modules'
            element={
            <MainLayout>
              <ModulesPage
              />
            </MainLayout>
        }
          />
          <Route
            path='/channels'
            element={
            <MainLayout>
              <ChannelsPage
              />
            </MainLayout>
        }
          />
          <Route
            path='/managements'
            element={
            <MainLayout>
              <ManagementsPage
              />
            </MainLayout>
        }
          />
          <Route
            path='/payments'
            element={
            <MainLayout>
              <PaymentPage
              />
            </MainLayout>
        }
          />
          <Route
            path="/start"
            element={
              <MainLayout>
                {''}
                <Welcome
                name={'admin'}
                />
                {''}
              </MainLayout>
          }
        />
        <Route
            path='/login'
            element={
             <LoginPage/>
        }
          />
            </Routes>
        </BrowserRouter>
  )
}
